### ISSUE TITLE
Quickstart Option 1: Not able to install shipyard

### ISSUE THREAD

**Issue by waza-ari** [shipyard/shipyard-deploy#24]
I am trying to install shipyard on a fresh docker installation, however, I cannot succeed:

```
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock shipyard/deploy start
Pulling image: shipyard/rethinkdb
error pulling shipyard image: invalid character 'c' looking for beginning of value
```

At this point, the installation process stops. Any idea what the problem is?

Ubuntu 14.04 LTS, docker.io "Docker version 1.0.1, build 990021a" from Ubuntu repositories

**Comment by mbentley** [comment]
That is a really old version of Docker.  I'm pretty certain that you will need to use the official Docker release (https://docs.docker.com/installation/ubuntulinux/).  Look under the 'Docker-maintained Package Installation' section.

**Comment by waza-ari** [comment]
Dumb. I'm sorry, you are right. Installing a current docker-maintained package solved the problem and installation went fine.

Sorry for this stupid question, could have found this issue myself...
