### ISSUE TITLE
shipyard-rethinkdb-data container

### ISSUE THREAD

**Issue by alexa-infra** [shipyard/shipyard-deploy#27]
Why do you run `shipyard-rethinkdb-data` container? As far as I understand that is Data Volume Container, and you create it to initialize the volume to use later in `shipyard-rethinkdb` container (by using `--volumes-from`). According to docs, since docker version 1.4.0 container volumes are initialized during `docker create` phase, and it is not required to `docker run` that data volume container (see examples in [docker create command](http://docs.docker.com/reference/commandline/cli/#create)). Is there any reason why do you run that container directly? I think it would be more clear to have 2 containers in `docker ps` list after deploying shipyard.

**Comment by funkytaco** [comment]
You opened this issue after the project was deprecated.
